### PR TITLE
Changing abbreviations f, fs, fo, fst

### PR DESCRIPTION
**Pull request by akella**
font: WAS: f, NOW: fo, (rare usage)
font-size: WAS: fz, NOW: fs
float: WAS: fl, NOW: f
font-style: WAS: fs, NOW: fst (rare usage)

Reason: the more abbreviations are used - the shorter and more straightforward  they should be.

### CODE REVIEW

**Comment by s10wen** [comment]
As well as `f` I have some more thoughts: https://github.com/sergeche/emmet-sublime/issues/533

What do you think?

**Comment by s10wen** [comment]
Please can anyone point me in the right direction of setting up my own custom shortcuts? E.g.

`c` = `cursor` -> `color`
`f` = `font` -> `float`
`p` = `position` -> `padding`

**Comment by s10wen** [comment]
I found a simple solution for this and created a gist, here are mine so far:
https://gist.github.com/s10wen/b2c839e725965ad11c1f

**Comment by CodeBrauer** [comment]
Why wasn't that implemented yet?

**Comment by sergeche** [comment]
Because it’s up to you how to customize your snippets.

**Pull request closed without merging**
