### PR TITLE
Fix #614

### LINKED ISSUE #614: URL not inserted into href for links
It seems https://github.com/microsoft/vscode/issues/54711 is still an issue on the latest Emmet.
Wrapping `www.google.it` with `a` should result in `<a href="www.google.it">www.google.it</a>`.

I'm guessing https://github.com/emmetio/py-emmet/commit/98fd8acb024bd8a9af23640989fa5776155f5f88 needs to be implemented on this repository?

### PR DESCRIPTION
**Pull request by rzhao271**
I tried translating over https://github.com/emmetio/py-emmet/commit/98fd8acb024bd8a9af23640989fa5776155f5f88 but I'm not sure how to run the tests for the abbreviation package.

### CODE REVIEW

**Comment by rzhao271** [comment]
Ok I got debugging set up. I'll continue working on this PR.

**Comment by rzhao271** [comment]
Ready to review @sergeche 
Added several tests so you can check whether the new behaviour is as expected.

**Comment by sergeche** [comment]
Looks good, thank you!

**Comment by sergeche** [comment]
Published as v2.2.0

**Pull request merged**
