### PR TITLE
Fix for issue#647 - Spacing and Cursor issue with expansions for gtc and gtr

### LINKED ISSUE #647: `gtc` expands with weird spacing
Currently for CSS and SASS, `gtc` expands to `grid-template-columns: ${1:repeat} ( );` instead of `grid-template-columns: ${1:repeat}();`.

Downstream issue: https://github.com/microsoft/vscode/issues/117648

### PR DESCRIPTION
**Pull request by AnuBhar**
**Issue:** On expanding gtc the result is grid-template-columns: repeat ( ). There is a space between repeat and ( ), so it doesn't recognize it as a normal style of css. Also, the cursor is placed after repeat and before the (). Similarly for gtr.

**Fix:**  Placed the cursor at the right position so that the expansion is correct. 

**Validation:** build succeeded, tests added and they pass. Verified on vscode. Below is the screenshot for the same.
Screenshot (16)

Fixes #647

### CODE REVIEW

**Comment by rzhao271** [comment]
I wonder if the `${0}` part also needs to be added for `minmax()`?

**Comment by essexgit** [comment]
I'm updated and I wondered when this fix will be released please?

**Comment by sergeche** [comment]
Thanks, published as emmet@2.3.5

**Comment by essexgit** [comment]
Thanks

**Pull request merged**
