### PR TITLE
Fix issue #574

### PR DESCRIPTION
**Pull request by devanshj**

### CODE REVIEW

**Comment by sergeche** [comment]
Looks great, thanks!

**Comment by devanshj** [comment]
@sergeche You're welcome! Also you're too fast Sergey, you merged before I could change the commit message and add the "Fixes #xyz" flag in description! xD

**Comment by sergeche** [comment]
Haha, yeah, was working on Emmet right now.
BTW, I made initial implementation of Emmet for Sublime Text, here’s how Emmet should work for users: https://github.com/emmetio/sublime-text-plugin
I might get back to VS Code to support such UX as well

**Comment by devanshj** [comment]
@sergeche Looks great! Also I hope you'll publish this PR soon so that I could make changes downstream.

**Comment by sergeche** [comment]
Done, published as `emmet@2.0.0-rc.7` or simply `emmet@rc`

**Comment by devanshj** [comment]
Thanks!

**Pull request merged**
