### PR TITLE
fixed bug: 'New line indentation off by one space or tab'

### PR DESCRIPTION
**Pull request by zstbsqx**
fixed 'New line indentation off by one space or tab'
see https://github.com/emmetio/brackets-emmet/issues/59
Thanks to @Miguel-Rodrigues

### CODE REVIEW

**Comment by alancolyer** [comment]
+1

**Comment by nunoarruda** [comment]
Why haven't this been merged yet?

**Comment by Donaldini** [comment]
Yes please merge this fix, I wouldn't want to make this fix locally every update :-)

**Comment by Donaldini** [comment]
Thanks @sergeche!

Maybe a silly question, but how do I get this fix to my Brackets application? I linked through from emmetio/brackets-emmet#59 and didn't realize I had changed to the Emmet lib.

The version of Emmet I have in Brackets is 1.2.2, but that is a version number I cannot find in this _Emmet repo_ (latest v1.3.0, 1.6.2 available) or the _brackes_emmet_ repo (latest v1.1.0)

**Comment by sergeche** [comment]
Try to re-install Brackets plugin. Emmet is a npm dependency of this plugin so it should install latest version as well. It everything works fine for you, I’ll update Brackets plugin with bumped version.

PS: the reason I’m being silent about Emmet updates lately it because I’m working on a completely new Emmet implementation with fresh codebase. I hope new version will fix most of the annoying bugs out there

**Comment by Donaldini** [comment]
Remove, reinstall didn't seem to have any effect. When I look at the Emmet files inside my _Application Support/Brackets/.../action/_ I do see that all files are new after reinstall, but the file in question has no update yet.

The package.json of that node_module says:   "version": "1.3.0", maybe because it isn't labeled as the _latest release_?

image

**Pull request merged**
