### PR TITLE
Add colon to Stylus separation value

### PR DESCRIPTION
**Pull request by corysimmons**
This is how most Stylus devs that I’ve met normalize Stylus libs: https://github.com/declandewet/stylus-conventions#which-syntax

### CODE REVIEW

**Comment by corysimmons** [comment]
@sergeche Care to review? Should be a quick one.

**Comment by corysimmons** [comment]
I would also mention that this is the syntax they use in the Stylus docs: https://github.com/LearnBoost/stylus/#example

**Comment by sheriffderek** [comment]
Here is an example to ponder:
screen shot 2015-03-10 at 7 47 16 am

I feel like the colons are *less* readable, but then again - out of all the times I find emmet useful, stylus is not one of them. It's so short already.

The only thing I see as a problem, is this syntax highlighting - which has nothing to do with emmet.

screen shot 2015-03-10 at 7 48 02 am

screen shot 2015-03-10 at 7 48 13 am

**Comment by sergeche** [comment]
Can’t accept this PR because it’s preferences-related and it’s a matter of taste

**Comment by corysimmons** [comment]
It's a preference in the first place so I don't see how switching preferences to a more common preference isn't mergeable.

**Comment by sheriffderek** [comment]
Single vs. Double quotes is a preference.@corysimmons - Maybe you make it a choice like this?

```json

{
 "html": {
    "attr_quotes" : "single"
  }
}

```

**Comment by sergeche** [comment]
@corysimmons at least @sheriffderek doesn’t agree with you, which makes 1:1 score.
If I accept this PR, what should I do when someone send another PR that revert this change? Do you have any stats about how many devs use colon vs. space?

**Comment by corysimmons** [comment]
@sergeche There's no way to find stats, but considering **all Stylus [docs](http://stylus-lang.com)** and **all the core libraries** ([nib](https://github.com/tj/nib/blob/master/lib/nib/border.styl), [etc.](https://github.com/mojotech/jeet/blob/master/stylus/jeet/_grid.styl#L28)) use this syntax, I'd say it would be the default preference.

**Comment by sergeche** [comment]
[not](http://stylus-lang.com/docs/css-style.html) [all](http://stylus-lang.com/docs/comments.html) [at](http://stylus-lang.com/docs/conditionals.html) [all](http://stylus-lang.com/docs/escape.html)

**Comment by corysimmons** [comment]
So on a few pages of the docs they use various syntaxes. Almost all core libs still use this syntax.

**Comment by corysimmons** [comment]
Meh, I'm done arguing. Keep the syntax whatever you want.

**Comment by kizu** [comment]
BTW, in Stylus 1.0, when it would be released, the colons would be mandatory. So it would be nice to change the default behaviour for Emmet now (you'll need to do this somewhere in the future anyway).

**Comment by sheriffderek** [comment]
Can we get a link to that? (just to be thorough) : )

**Comment by kizu** [comment]
There is a mention to it in wiki regarding plans for 1.0.0, see the fourth item at [“What to change in syntax”](https://github.com/LearnBoost/stylus/wiki/1.0.0#what-to-change-in-syntax), for example:

> We should remove the support for `property value` syntax.

**Comment by corysimmons** [comment]
@kizu Awesome. Good change.

@sergeche care to merge now?

**Comment by sheriffderek** [comment]
I'm not on a *side* really (*I do generally prefer less keystrokes/tabs/single-quotes etc*)... but If it's going ```html:```- I was going to start *now*, before I end up having to manually add :'s everywhere across 20 projects... *however* - I don't see enough evidence, that one persons note on the wiki, will actually result in this change. I'm going to try and find out how likely this really is.

**Comment by corysimmons** [comment]
@sheriffderek @kizu is the maintainer of Stylus and one of the lead contributors to Stylus is already working on this https://github.com/LearnBoost/stylus/issues/1858#issuecomment-78295123

**Comment by sheriffderek** [comment]
Oh. *well* - I had just seen last edited "Dec 30, 2013" and only 2 revisions. Seems like *you* are the most interested in this. You should put a few other characters in there while you're at it. How about `background---> red` lol. But thanks for the follow up. I'll keep my eye on this to figure out when the intern will need to spend the week pasting `:`'s into our projects. : )

**Comment by kizu** [comment]
Other than in wiki (this page is rather old, sure) it was mentioned a bunch of times in different issues, but I'm lazy enough to look the links up for now. Also: it is strange to talk about any extra characters when speaking in Emmet context, where you won't ever write those characters anyway :)

**Comment by sheriffderek** [comment]
Well - I don't use emmet with stylus - so I'm moving my question over to stylus. Thanks.

**Pull request closed without merging**
