### PR TITLE
Add a filter for jsx

### PR DESCRIPTION
**Pull request by murphyrandle**
Add very basic JSX support.

Yay commit

For now it just transforms class= to className=
and for= to htmlFor=

### CODE REVIEW

**Comment by murphyrandle** [comment]
Also, I wasn't able to figure out how to apply the jsx filter automatically when I'm editing a file with a jsx extension. Would have to do with the editor plugin?

**Comment by murphyrandle** [comment]
@sergeche I'm sure you're very busy. Have you had any time to take a look at this?

**Comment by sergeche** [comment]
Yeah, sorry, been very busy. Current solution looks very hacky and may produce unpredictable results.
The ultimate solution is to walk on each node, rename attributes and then simply pass to `html` filter.

In other words, your filter may look like this:

```
define(function(require, exports, module) {
	var attrMap = {
		'class': 'className',
		'for': 'htmlFor'
	};

	return function process(tree) {
		tree.children.forEach(function(item) {
			item._attributes.forEach(function(attr) {
				if (attr.name in attrMap) {
					attr.name = attrMap[attr.name]
				}
			});
			process(item);
		});

		return tree;
	};
});
```

And you should use it together with `html` filter, like so:

```
"jsx": {
	"filters": "jsx, html",
	"extends": "html",
	"profile": "xml"
}
```

**Comment by murphyrandle** [comment]
@sergeche really sorry that I got busy elsewhere and never got back to making those suggested changes :(

**Comment by sergeche** [comment]
No problem :) Thank you, I’m going to improve JSX support since I’m going to write some React soon :)

**Comment by murphyrandle** [comment]
Great! That's wonderful :)

**Pull request merged**
